# Generated by Django 5.1.4 on 2024-12-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_keylog_remove_videolog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='file_type',
            field=models.CharField(default='audio', max_length=10),
        ),
        migrations.AlterField(
            model_name='videolog',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
