# Generated by Django 5.1.4 on 2025-01-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_videolog_file_type_alter_videolog_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='file_metadata',
            field=models.CharField(default='yt_audio', max_length=100),
        ),
    ]
