# Generated by Django 5.1.4 on 2025-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_videolog_file_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolog',
            name='batch_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
